### ISSUE TITLE
Consent on scroll doesn't work

### ISSUE THREAD

**Issue by herkulano** [NoriSte/gatsby-plugin-iubenda-cookie-footer#1]
I have the option:
```
consentOnScroll: "false"
```
It doesn't work, as I start scrolling it closes the banner.

**Comment by herkulano** [comment]
@NoriSte thank you so much! I completely missed the fact that I had `false` as a string instead of a boolean! 😳

**Comment by NoriSte** [comment]
Don't worry @herkulano, it happens 😊👋
