### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by fabri86** [NoriSte/gatsby-plugin-iubenda-cookie-footer#284]
Hi, 
first of all thanks a lot for your useful plugin.

As a company we purchased yesterday the services provided by IUBENDA for our website, which shall support 4 languages. Is there currently 'any chance'/'any open development activity' to support multiple languages? In the readme and in the code I could not find anything about yet, but I might we wrong.

Thanks a lot
Fabrizio

**Comment by NoriSte** [comment]
Hi @fabri86, thank you!!
Has Iubenda changed anything related to language management? In the very first example of the readme there is an example setting the language, isn't it working for you use case?
Stefano

**Comment by fabri86** [comment]
Hi, thanks for your answer.
Checking the readme is the first thing I have done.
If like recommended in the readme, I have the chance to set exclusively one language at the time.
I rather would like to pass a set of iubenda-option objects, one per each language. 
If I try to include multiple times the configuration once per each specific language, the last included wins.

I do not see at the moment a way to support multiple languages simultaneously, once the user decides to switch to a different language in the website.

![image](https://user-images.githubusercontent.com/17066478/77149696-7772c080-6a92-11ea-9a56-6dcc2f6a1328.png)

Is there something I am doing wrong or something you have not considered for now?
Thanks a lot
Kind regards
Fabrizio

**Comment by NoriSte** [comment]
Thanks, now it's clear!
Adding multi-language support is not on the road but it would be easy, would you like to submit a PR? 😊

**Comment by fabri86** [comment]
Well.. I feel excited :)
Actually I have the simple improvement and a PR ready to be submitted reviewed by your team. 
Build is ok, however I get an error when I try to run 'npm  run plugin:link' (I am on a Windows machine). This is what I get: 

![image](https://user-images.githubusercontent.com/17066478/77204519-31017e00-6af3-11ea-807a-ac489a12c20d.png)
rm: cannot remove './node_modules/gatsby-plugin-iubenda-cookie-footer': Is a directory
 
OR 

![image](https://user-images.githubusercontent.com/17066478/77204312-c0f2f800-6af2-11ea-86bf-2733368822ab.png)


ln: failed to create symbolic link './node_modules/gatsby-plugin-iubenda-cookie-footer' -> '../../../': File name too long

Any idea? I am not able basically run the scripts on the test-projects and verify the tests...
Thanks a lot, in the meantime I will open a PR

**Comment by NoriSte** [comment]
First of all: well done Fabrizio 😊
Have you already written the test but you can't run any of them I guess...
The next step could be to make the Unix-based commands more cross platform, do you feel comfortable doing that?
Looking forward you your PR
Stefano

**Comment by fabri86** [comment]
Hey Stefano, thanks :)
Well, at the moment I have not written yet any test cause I cannot neither run the existing ones.
I am definitely not familiar with Unix, but i can try to understand what this is all about.

I opened anyway a PR in the meantime. 
Fabrizio

**Comment by fabri86** [comment]
Hi again,
I have tried to add support for symbolic links and to run the command from an ubuntu shell, however I have not achieved what I wanted. Basically I confirm not to be able to run the existing test probably due to the Unix-based commands as you said.
Can anything be done from your side/team to facilitate my main goal, which is just adding the support for the multi-language iubenda configurations? 
Unfortunately I am rather focused on the MVP product and I am just walking in the darkness here :)

Thanks a lot

**Comment by NoriSte** [comment]
Yes, please drive me:
- to understand how Iubenda must be configured to use multiple language
- how I can systematically load the site showing a language or another one (how Iubenda is showed with a language or another one?)
If the effort isn't huge I'll add it for you postponing the crossplatform support 😉

**Comment by fabri86** [comment]
Hi Stefano,
I spent some time in the weekend to verify what the support told me last time, however there must be something still unclear or ineffective from my side. 

Since we are using Contentful as a CMS, the only possible approach for our project would be integrating the script in the head tag of the website, I noticed that when I add in the head of the website all the language-specific scripts to be supported, the last one wins. 
For instance if I need to support English and German and I include both the language-specific scripts in the head, I will get the banner in German just because it is the last script being executed. 
Of course this is not what we want and therefore I am planning to have a consultation with the iubenda team to get their advice. 

I will come back to you.
Thanks for now

**Comment by NoriSte** [comment]
Ok @fabri86 thanks for the heads up, looking forward to your conclusion/solution. I temporarily closed the PR, feel free to reopen it.
Best
Stefano

**Comment by fabri86** [comment]
Hi Stefano, 
you did good by closing temporary the PR.
For some complications that I could not face at the moment I have decided to solve the issue in a 
different way by creating within my code the scripts and by adding them to the document head. 
To support who ever else finss himself in such a situation, I report here below a guide recommended from iubenda team to integrate manually the scripts, if you do not mind:

https://www.iubenda.com/en/help/834-cookie-solution-multilingua-con-wordpress#senza-plugin

Thanks a lot for your availability and sorry for the time spent !
All the best

Fabrizio
