### ISSUE TITLE
Race condition in isIubendaConsentGiven()

### ISSUE THREAD

**Issue by musomatt** [NoriSte/gatsby-plugin-iubenda-cookie-footer#430]
We've noticed in Sentry that we're seeing the following error coming from the plugin: 
`Cannot read property 'api' of undefined`.

This is down to the [check being made](https://github.com/NoriSte/gatsby-plugin-iubenda-cookie-footer/blob/master/src/gatsby-browser.js#L12) in `isIubendaConsentGiven()`. It currently checks that `._iub` exists on the window but it does not check if `window._iub.cs` has a value.

After looking into this, it looks like `.cs` is not added to the `._iub` object until `iubenda_cs.js` has loaded (which in turn loads another core file from Iubenda). If the user lands on the website and navigates to a different page before Iubenda has finished loading it satisfies the current condition in `isIubendaConsentGiven()` yet the `.cs` property has not been added, causing the error.

I put together a quick PR but I'm unable to push a new branch due to permissions.

**Comment by NoriSte** [comment]
Hi @musomatt 
Thanks for reporting it! Instead of trying pushing the branch on this repo, fork it and raise a PR by comparing this repo's master to your repo's new branch 😉

**Comment by NoriSte** [comment]
@musomatt did you manage doing it?

**Comment by NoriSte** [comment]
Published the new version containing the fix 😉

**Comment by musomatt** [comment]
Apologies, I missed these messages 😦 

Thank you for shipping the fix, much appreciated 💯

**Comment by NoriSte** [comment]
You're welcome 😊
