### ISSUE TITLE
"Page Not Found" on Netlify

### ISSUE THREAD

**Issue by koalatative** [NoriSte/gatsby-plugin-iubenda-cookie-footer#470]
My site is running on Netlify, the consent banner works as expected but when I click the "Learn more and customize" button or the small tracking preferences widget, the overlay says "Page Not Found". Is there another step in setting this up for the whole cookie solution to work with Netlify?

**Comment by NoriSte** [comment]
Hi
Could you provide some screenshots, please? Is the Iubenda's widget that recognizes you as the Iubenda's admin and shows a "customize" link that brings to Iubenda's admin panel? Or is Iubenda's admin panel link that brings to Netlify?
Thanks
Stefano

**Comment by koalatative** [comment]
Yeah sure, I don't think it has anything to do with the admin panel.

The button I'm talking about is this one:
![image](https://user-images.githubusercontent.com/71134212/120222573-cf858500-c248-11eb-8349-c4d50614ed36.png)

It should bring up a window that looks like this:
![image](https://user-images.githubusercontent.com/71134212/120222617-e1ffbe80-c248-11eb-8a7b-64b154d303e5.png)

But instead the popup just Netlify's page not found content. So it seems like whatever is supposed to show in the popup isn't recognized by Netlify.

**Comment by NoriSte** [comment]
Can you share a minimal site example where I can play with it? What does the network panel say?

**Comment by koalatative** [comment]
> Can you share a minimal site example where I can play with it? What does the network panel say?

I'll take a look at the network panel and get back to you. Not sure if I'll have time to put together an example until later this week or next. I'm also in contact with iubenda support so we'll see how that goes.

Have you seen examples of this plugin's tracking preferences screen working as expected on Netlify?

**Comment by NoriSte** [comment]
> Have you seen examples of this plugin and iubenda's tracking preferences screen working as expected on Netlify?

I didn't receive complains until now 😶

**Comment by koalatative** [comment]
> I didn't receive complains until now 😶

Heh k good to know. First response from iubenda was that I need to pay for their cookie policy, but they also didn't realize that those buttons are supposed to take the user to the tracking preferences screen (cookie policy is a different link), so I'm waiting for clarification.

**Comment by NoriSte** [comment]
Ok! Meanwhile, I close the issue, feel free to re-open it and keep me posted 😉
