### ISSUE TITLE
Support for Gatsby v4

### ISSUE THREAD

**Issue by cdt-team** [NoriSte/gatsby-plugin-iubenda-cookie-footer#489]
Hello, it's possibile to make this package compatible with Gatsby v4?

Thanks.

**Comment by cdt-team** [comment]
It's seems to be enough to update the peerDependencies in package.json, but I haven't tested all plugin functionalities.

**Comment by NoriSte** [comment]
Hi! It's already compatible with V4, isn't it?

From the [main package.json, line 44](https://github.com/NoriSte/gatsby-plugin-iubenda-cookie-footer/blob/master/package.json#L44)
```json
"peerDependencies": {
  "gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0"
}
```

**Comment by cdt-team** [comment]
Hi! I try to re-install this plugin, when i run **yarn add gatsby-plugin-iubenda-cookie-footer** get this message:
`warning " > gatsby-plugin-iubenda-cookie-footer@1.3.1" has incorrect peer dependency "gatsby@^2.0.0 || ^3.0.0".`

Also when I run **gastby develop** 
`_Plugin gatsby-plugin-iubenda-cookie-footer is not compatible with your gatsby version 4.8.0 - It requires gatsby@^2.0.0 || ^3.0.0_
`
And if I go to explore the package.json of your project in my **node:modules** folder, peer dependencies are 

```
"peerDependencies": {
    "gatsby": "^2.0.0 || ^3.0.0"
  }
```
I see your package.json, this's strange... I have run yarn cache clear.

**Comment by NoriSte** [comment]
My bad, I hadn't published it! Please try now with the `1.4.0` version

**Comment by cdt-team** [comment]
Not it works.
Thank for your time!

**Comment by NoriSte** [comment]
Thank you for reporting, and sorry for the mistake 😊
