### ISSUE TITLE
Custom preferences button instead of automatically added floating button

### ISSUE THREAD

**Issue by nimame** [NoriSte/gatsby-plugin-iubenda-cookie-footer#491]
The iubenda widget offers to optionally hide the floating button and instead add a custom link that opens it (see [docs](https://www.iubenda.com/en/help/3831-customize-cookie-banner#customizing-style-text)). If I understand correctly, for this the `floatingPreferencesButtonDisplay` config setting needs to be set to `false` and a link with the class `iubenda-cs-preferences-link` needs to be added to the site. I did both in my Gatsby app using this plugin, but it is not working. The floating button is not displayed, but clicking my link does also not open the widget.

Is this a limitation of this plugin or am I missing something?

**Comment by NoriSte** [comment]
Not sure... Can you please share a minimal repo with
1. a standard gatsby site with the Iubenda feature you need that works
2. a gatsby site that uses this plugin that shows that the Iubenda feature you need does not work

?

**Comment by NoriSte** [comment]
@nimame I close this issue due to inactivity, feel free to reopen it 😊
