### ISSUE TITLE
Gatsby 5 support

### ISSUE THREAD

**Issue by nimame** [NoriSte/gatsby-plugin-iubenda-cookie-footer#493]
According to the `package.json` this package supports Gatsby v2 - v4. Are the maintainers planning to add v5 support? 

Thanks for sharing this btw!

**Comment by NoriSte** [comment]
Thank you, I forgot to update this issue 😊

**Comment by nimame** [comment]
Thanks for resolving it - and sorry I wasn't able to help :)
